Repository googleapis/java-shell, pull requests merged in 2021-09, with the labels that each got.

#80 chore: remove readme autosynth config
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: automerge, kokoro:force-run, cla: yes, api: cloudshell

#87 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  renovate.json
Labels: cla: yes, api: cloudshell

#99 chore: change branch master to main in github configurations
  .github/sync-repo-settings.yaml
Labels: automerge, cla: yes, api: cloudshell
